name: "Conventional Commits"
description: "Ensures that all commit messages are following the conventional-commits standard."
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: false
runs:
  using: 'node16'
  steps:
    - name: Run action
      shell: bash
      run: |
        yes | npx tsx ./src/main.ts